provider:
  name: faas
  gateway: http://68.183.211.211:31112/

functions:
  inception:
    lang: dockerfile
    handler: ./function
    image: alexellis/inception:2.1
    constraints:
      - "type=rasp"
