provider:
  name: faas
  gateway: http://http://178.128.194.203:31112/

functions:
  inception:
    lang: dockerfile
    handler: ./function
    image: alexellis/inception:2.1
    constraints:
      - "type=rasp"
